FROM python:3.14-slim

WORKDIR /app

COPY requirements/train.txt requirements/train.txt

RUN pip install --no-cache-dir -r requirements/train.txt

COPY src/ src/
COPY configs/ configs/

RUN mkdir -p /app/data /app/checkpoints

CMD ["python", "-m", "src.train"]